server:
  port: 8000
spring:
  application:
    name: cambio-service  
  datasource:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas:  cambio_service
    user: root
    password: admin123