spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_person?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

