server:
  port: 8000
eureka:
  client:
    service-url:  
      defaultZone:  http://localhost:8761/eureka  
spring:
  application:
    name: cambio-service  
  datasource:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas:  cambio_service
    user: root
    password: admin123
    locations: classpath:db/migration
management:
  tracing:
    sampling:
      probability: 1.0	
#springdoc:
#  api-docs:
#    path: cambio-service/v3/api-docs
#  show-actuator: true
#  swagger-ui:
#    config-url: /cambio-service/v3/api-docs/swagger-config 
#    url:  /cambio-service/v3/api-doc  