services:
  naming-server:
    image: patrickro24/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - patrick-network  
  api-gateway:
    image: patrickro24/api-gateway:0.0.1-SNAPSHOP
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE.URL: http://zipkin-server:9411/    
    networks:
      - patrick-network
  cambio-service:
    image: patrickro24/cambio-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE.URL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
      SPRING.FLYWAY.LOCATIONS: classpath:db/migration
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - patrick-network
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - patrick-network   
  cambio-db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3306  # Mapear porta externa (host) para a porta padrão interna do MySQL
    networks:
      - patrick-network
  book-db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3306  # Mapear porta externa (host) para a porta padrão interna do MySQL
    networks:
      - patrick-network  
networks: 
  patrick-network:
    driver: bridge  