services:
  naming-server:
    image: patrickro24/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - patrick-network 
      
  api-gateway:
    image: patrickro24/api-gateway:0.0.1-SNAPSHOP
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0      
    networks:
      - patrick-network
      
  cambio-service:
    image: patrickro24/cambio-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2&allowPublicKeyRetrieval=true
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2&allowPublicKeyRetrieval=true
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
      SPRING.FLYWAY.LOCATIONS: classpath:db/migration
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - patrick-network
      
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - patrick-network
      
  cambio-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
    ports:
      - 3308:3306  # Mapear porta externa (host) para a porta padrão interna do MySQL
    networks:
      - patrick-network
      
  book-db:
    image: mysql:8.0.28
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
    ports:
      - 3310:3306  # Mapear porta externa (host) para a porta padrão interna do MySQL
    networks:
      - patrick-network
      
networks: 
  patrick-network:
    driver: bridge  