server:
  port: 8888
  
spring:
  application:
    name: config-server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Patrickriibeiro/config-server
          #username: user git 
          #password: pass git
          default-label: main
          search-paths:
          - 'greeting-service*'